"""
Flora Carbon AI - PDF audit/certificate report generation.
Pure-Python via reportlab (no native/system dependencies), kept separate from
detector.py so the core detection engine has no PDF-specific imports.
"""

import io
import time
from typing import Dict, Any

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

EMERALD = colors.HexColor("#10B981")
DARK_BG = colors.HexColor("#0B1710")


def generate_pdf_report(result: Dict[str, Any], filename: str, annotated_jpeg_bytes: bytes) -> bytes:
    """
    Renders a one-page audit certificate for a single analyze_tree_canopy() result:
    title/timestamp, KPI table, the annotated image, and the audited limitations.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=18 * mm, bottomMargin=18 * mm, leftMargin=18 * mm, rightMargin=18 * mm
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "FloraTitle", parent=styles["Title"], textColor=EMERALD, fontSize=20, spaceAfter=4
    )
    meta_style = ParagraphStyle(
        "FloraMeta", parent=styles["Normal"], textColor=colors.grey, fontSize=9, spaceAfter=14
    )
    section_style = ParagraphStyle(
        "FloraSection", parent=styles["Heading2"], textColor=EMERALD, fontSize=13, spaceBefore=14, spaceAfter=6
    )
    body_style = styles["BodyText"]

    metrics = result.get("metrics", {})
    story = []

    story.append(Paragraph("Flora Carbon AI &mdash; Canopy Audit Certificate", title_style))
    story.append(Paragraph(
        f"Source: {filename} &nbsp;|&nbsp; Generated: {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())} "
        f"&nbsp;|&nbsp; Engine: {result.get('model_source', 'Spectral Engine')}",
        meta_style
    ))

    story.append(Paragraph("Telemetry Summary", section_style))
    kpi_rows = [
        ["Tree Count", str(metrics.get("tree_count", 0))],
        ["Total Canopy Area", f"{metrics.get('total_canopy_m2', 0.0):,.2f} m^2"],
        ["Canopy Cover", f"{metrics.get('canopy_cover_percentage', 0.0):.2f} %"],
        ["Canopy Class", metrics.get("canopy_density_class", "N/A")],
        ["Estimated AGB", f"{metrics.get('estimated_agb_tons', 0.0):,.2f} t"],
        ["Inferred CO2e", f"{metrics.get('inferred_co2e_tons', 0.0):,.2f} t CO2e"],
        ["Ground Sampling Distance", f"{metrics.get('gsd', 0.0)} m/px"],
    ]
    table = Table(kpi_rows, colWidths=[70 * mm, 90 * mm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#E8F7EF")),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#123321")),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#B7E4CB")),
    ]))
    story.append(table)

    if annotated_jpeg_bytes:
        story.append(Paragraph("Annotated Orthomosaic", section_style))
        img_buffer = io.BytesIO(annotated_jpeg_bytes)
        rl_img = RLImage(img_buffer, width=174 * mm, height=174 * mm * 0.6, kind="proportional")
        story.append(rl_img)

    limitations = result.get("limitations", [])
    if limitations:
        story.append(Paragraph("Audited Model Limitations", section_style))
        for lim in limitations:
            story.append(Paragraph(
                f"<b>{lim.get('title', '')}</b> ({lim.get('severity', '')}): {lim.get('description', '')}",
                body_style
            ))
            story.append(Spacer(1, 4))

    story.append(Spacer(1, 12))
    story.append(Paragraph(
        "This certificate is generated by an automated spectral remote-sensing model and is "
        "intended for preliminary assessment only. It is not a substitute for field-verified "
        "carbon accounting under a formal registry methodology.",
        meta_style
    ))

    doc.build(story)
    return buffer.getvalue()
